// <auto-generated />
namespace FileHistorian.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Datetime2Refactor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Datetime2Refactor));
        
        string IMigrationMetadata.Id
        {
            get { return "201707012046081_Datetime2Refactor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
